sudo: false
language: bash

os:
  - linux

cache:
  directories:
    - "~/.platformio"

install:
  - pip install --user -U pip
  - pip install --user -U platformio

before_script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x *.sh *.py
script:
  - cd $TRAVIS_BUILD_DIR
  - sed -n '118,136p;137q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/\/\/#define ENABLE_BLUETOOTH/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/#define ENABLE_BLUETOOTH/\/\/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/\/\/#define ENABLE_WIFI/#define ENABLE_WIFI/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -n '118,136p;137q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - PLATFORMIO_BUILD_FLAGS=-DMACHINE_FILENAME=test_drive.h platformio run
  - sed -i "s/\/\/#define ENABLE_BLUETOOTH/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/#define ENABLE_WIFI/\/\/#define ENABLE_WIFI/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -n '118,136p;137q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - PLATFORMIO_BUILD_FLAGS=-DMACHINE_FILENAME=test_drive.h platformio run
  - sed -i "s/\/\/#define ENABLE_BLUETOOTH/#define ENABLE_BLUETOOTH/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -i "s/\/\/#define ENABLE_WIFI/#define ENABLE_WIFI/g" $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - sed -n '118,136p;137q' $TRAVIS_BUILD_DIR/Grbl_Esp32/config.h
  - ./build-all.sh

notifications:
  email:
    on_success: change
    on_failure: change
