sudo: false
language: python

os:
  - linux

cache:
  directories:
    - "~/.platformio"

install:
  - pip install --user -U pip
  - pip install --user -U platformio

script:
  - ./configure-features.py -e WIFI -d BLUETOOTH
  - ./build-machine.py test_drive.h
  - ./configure-features.py -e BLUETOOTH -d WIFI
  - ./build-machine.py test_drive.h
  - ./configure-features.py -e BLUETOOTH WIFI
  - ./build-all.py

notifications:
  email:
    on_success: change
    on_failure: change
